---
# - name: Setup Docker on all host
#   hosts: all
#   become: true
#   gather_facts: false

#   roles:
#     - common


# - name: Setup host
#   hosts: localhost
#   become: true
#   gather_facts: false
#   roles:
#     - db
#     - lb

- name: Setup flask, nginx
  hosts: all
  become: true
  gather_facts: false
  roles:
    - api
    # - web

- name: Create network on node1
  hosts: node1
  become: true
  gather_facts: false
  tasks:
    - name: Create network
      docker_network:
        name: webapp_network
        connected:
          - flask
          - webserver

- name: Create network on localhost
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Create network
      docker_network:
        name: webapp_network
        connected:
          - flask
          - webserver
          - mongodb
          - loadbalance

# - name: Forward 8001 port to port 8000 of node
#   hosts: node1
#   become: true
#   gather_facts: false
#   tasks:
#     - shell: |
#         socat tcp-listen:8001,bind=192.168.40.128,fork tcp:192.168.40.134:8000 &

