---
# - name: Setup Docker on all host
#   hosts: all
#   become: true
#   gather_facts: false

#   roles:
#     - common


- name: Setup host
  hosts: localhost
  become: true
  gather_facts: false

  roles:
    - db
    - lb

- name: Setup flask, nginx and create network
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Create network
      docker_network:
        name: webapp_network
        connected:
          - flask
          - webserver
          - mongodb
          - loadbalance

- name: Forward 27017 port of node
  hosts: ubuntu4
  become: true
  gather_facts: false

  shell: |
    socat tcp-listen:27017,bind=127.0.0.1,fork tcp:192.168.40.128:27017

