---
- name: Create folder
  ansible.builtin.file:
    path: /etc/loadbalance
    state: directory
    mode: '0755'

- name: Copy files
  ansible.builtin.copy:
    src: files
    dest: /etc/loadbalance
    mode: '0644'

- name: Build Loadbalancing container image
  docker_image:
    name: nginx-lb
    build:
      path: /etc/loadbalance/files
    source: build
    state: present

- name: Build container
  docker_container:
    name: loadbalance
    image: nginx-lb   
    restart_policy: unless-stopped
    ports:
      - "80:80"
    volumes:
      - nginxdata:/var/log/nginx
    network_mode: bridge