name: CI

on:
  push:
    branches:
      - midterm
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          cd 10.Midterm/Docker/app
          pip install -r requirements.txt;

      - name: Create Container
        run: |
          cd 10.Midterm/Docker/app
          docker compose build
          docker compose up

      - name: Test with pytest
        run: |
          cd 10.Midterm/Docker/app
          pytest test.py